# Configuration for Repo Lockdown - https://github.com/dessant/repo-lockdown

name: 'Repo Lockdown'

on:
  pull_request_target:
    types: opened

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: dessant/repo-lockdown@0b093279a77b44bbc38e85089b5463dd06b4aea4 # v2.2.0
        with:
          pr-comment: |
            Thank you for your interest in the QEMU project.

            This repository is a read-only mirror of the project's repostories hosted
            on https://gitlab.com/qemu-project/qemu.git.
            The project does not process merge requests filed on GitHub.

            QEMU welcomes contributions of code (either fixing bugs or adding new
            functionality). However, we get a lot of patches, and so we have some
            guidelines about contributing on the project website:
            https://www.qemu.org/contribute/
          lock-pr: true
          close-pr: true
